framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing: { }

        # Définition du bus par défaut
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                default_middleware: allow_no_handlers
